package controller.controlfiles;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

/**
 * The Photo class is extend the ControlFile to accept more functionality. In this case, Photo class
 * can generate a bufferedImage which could be edit or show by other future classes.
 *
 * @author XIAWEI ZHANG
 * @author Yu Feng Gan
 */
public class Photo extends ControlFile {

  /** The height of this Photo Class. */
  private int height;

  /** The Width of this Photo Class. */
  private int width;

  /** The BufferedImage generated by this photo Class. */
  private BufferedImage bufferedImage;

  /**
   * The Photo Constructor to store the Photo's name, location, and tags and initialize the height
   * and width for bufferedImage.
   *
   * @param fileName a String containing the original file name of the Controlled File
   * @param location String containing the path to the designated the Controlled File
   * @param tags a String containing all the tags in the Controlled File
   */
  public Photo(String fileName, String location, String tags) {
    super(fileName, location, tags);

    try {
      bufferedImage = ImageIO.read(new File(location + File.separator + getFullName()));
      height = bufferedImage.getHeight();
      width = bufferedImage.getWidth();
    } catch (IOException ex) {
      System.out.println("photo not found");
    }
  }

  /**
   * The Getter method to get the BufferedImage of this Photo class.
   *
   * @return BufferedImage
   */
  public BufferedImage getBufferedImage() {
    return bufferedImage;
  }

  /**
   * The Getter method to get the Height of this Photo's BufferedImage.
   *
   * @return int The height of this Photo's BufferedImage
   */
  public int getHeight() {
    return height;
  }

  /**
   * The Getter method to get the Height of this Photo's BufferedImage.
   *
   * @return int The width of this Photo's BufferedImage
   */
  public int getWidth() {
    return width;
  }
}
